// Generated by `bun run semantics-version` (tools/semantics-version.ts); do not edit by hand.
/** Content hash of `src/semantics/*.ts`. Changes whenever the semantic functions or their default parameters change. */
export const SEMANTICS_VERSION = "35e15fdf54f37ec1"
