/**
 * Writes `src/semanticsVersion.ts`: a content hash of `src/semantics/*.ts` (names + bytes, CRLF folded to LF).
 * `bun run semantics-version` regenerates it; `test/semanticsVersion.test.ts` fails when it is stale.
 */
import { createHash } from "node:crypto"
import { readdirSync, readFileSync, writeFileSync } from "node:fs"
import { join } from "node:path"

const root = join(import.meta.dir, "..")

export const hashSemantics = (dir = join(root, "src", "semantics")): string => {
  const h = createHash("sha256")
  for (const f of readdirSync(dir).filter((n) => n.endsWith(".ts")).sort()) {
    h.update(f).update("\0").update(readFileSync(join(dir, f), "utf8").replace(/\r\n/g, "\n")).update("\0")
  }
  return h.digest("hex").slice(0, 16)
}

export const render = (version: string): string =>
  `// Generated by \`bun run semantics-version\` (tools/semantics-version.ts); do not edit by hand.\n` +
  `/** Content hash of \`src/semantics/*.ts\`. Changes whenever the semantic functions or their default parameters change. */\n` +
  `export const SEMANTICS_VERSION = "${version}"\n`

if (import.meta.main) {
  const out = join(root, "src", "semanticsVersion.ts")
  writeFileSync(out, render(hashSemantics()))
  console.log(`wrote ${out}`)
}
