// The editor features a query editor needs, instead of `editor.all.js` (every Monaco feature, ~2.5 MB
// minified). Anything not listed here (diff editor, code lens, colour picker, sticky scroll, inline
// completions, rename, drag and drop, …) is not shipped. To add a feature, import its contribution here.
import "monaco-editor/esm/vs/editor/browser/coreCommands.js"
import "monaco-editor/esm/vs/editor/browser/widget/codeEditor/codeEditorWidget.js"
import "monaco-editor/esm/vs/editor/contrib/bracketMatching/browser/bracketMatching.js"
import "monaco-editor/esm/vs/editor/contrib/clipboard/browser/clipboard.js"
import "monaco-editor/esm/vs/editor/contrib/codeAction/browser/codeActionContributions.js"
import "monaco-editor/esm/vs/editor/contrib/comment/browser/comment.js"
import "monaco-editor/esm/vs/editor/contrib/contextmenu/browser/contextmenu.js"
import "monaco-editor/esm/vs/editor/contrib/cursorUndo/browser/cursorUndo.js"
import "monaco-editor/esm/vs/editor/contrib/find/browser/findController.js"
import "monaco-editor/esm/vs/editor/contrib/folding/browser/folding.js"
import "monaco-editor/esm/vs/editor/contrib/format/browser/formatActions.js"
import "monaco-editor/esm/vs/editor/contrib/gotoSymbol/browser/goToCommands.js"
import "monaco-editor/esm/vs/editor/contrib/gotoSymbol/browser/link/goToDefinitionAtPosition.js"
import "monaco-editor/esm/vs/editor/contrib/gotoError/browser/gotoError.js"
import "monaco-editor/esm/vs/editor/contrib/hover/browser/hoverContribution.js"
import "monaco-editor/esm/vs/editor/contrib/indentation/browser/indentation.js"
import "monaco-editor/esm/vs/editor/contrib/inlayHints/browser/inlayHintsContribution.js"
import "monaco-editor/esm/vs/editor/contrib/lineSelection/browser/lineSelection.js"
import "monaco-editor/esm/vs/editor/contrib/linesOperations/browser/linesOperations.js"
import "monaco-editor/esm/vs/editor/contrib/links/browser/links.js"
import "monaco-editor/esm/vs/editor/contrib/multicursor/browser/multicursor.js"
import "monaco-editor/esm/vs/editor/contrib/parameterHints/browser/parameterHints.js"
import "monaco-editor/esm/vs/editor/contrib/placeholderText/browser/placeholderText.contribution.js"
import "monaco-editor/esm/vs/editor/contrib/readOnlyMessage/browser/contribution.js"
import "monaco-editor/esm/vs/editor/contrib/smartSelect/browser/smartSelect.js"
import "monaco-editor/esm/vs/editor/contrib/snippet/browser/snippetController2.js"
import "monaco-editor/esm/vs/editor/contrib/suggest/browser/suggestController.js"
import "monaco-editor/esm/vs/editor/contrib/tokenization/browser/tokenization.js"
import "monaco-editor/esm/vs/editor/contrib/toggleTabFocusMode/browser/toggleTabFocusMode.js"
import "monaco-editor/esm/vs/editor/contrib/unicodeHighlighter/browser/unicodeHighlighter.js"
import "monaco-editor/esm/vs/editor/contrib/wordHighlighter/browser/wordHighlighter.js"
import "monaco-editor/esm/vs/editor/contrib/wordOperations/browser/wordOperations.js"
import "monaco-editor/esm/vs/editor/common/standaloneStrings.js"
import "monaco-editor/esm/vs/base/browser/ui/codicons/codiconStyles.js"
